name: solidblocks

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'pelle'
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  SKIP_TESTS: ${{ contains(github.event.head_commit.message, '#documentation-update') }}

concurrency:
  group: solidblocks
  cancel-in-progress: false

permissions:
  pages: write
  id-token: write
  contents: write
  packages: write

jobs:
  solidblocks-shell:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - name: install bzip2
        run: sudo apt-get install -y bzip2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: solidblocks-shell/do build
      - name: Test
        run: solidblocks-shell/do test
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-shell
          path: |
            solidblocks-shell/build/solidblocks-shell-*.zip
            solidblocks-shell/build/snippets/*

  solidblocks-cloud-init:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      HETZNER_DNS_API_TOKEN: ${{ secrets.HETZNER_DNS_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: solidblocks-cloud-init/do build
      - name: Test
        run: solidblocks-cloud-init/do test
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-cloud-init
          path: |
            solidblocks-cloud-init/build/solidblocks-cloud-init-*.zip
            solidblocks-cloud-init/build/snippets/*

  solidblocks-hetzner-nuke:
    runs-on: ubuntu-latest
    needs:
      - solidblocks-shell
      - solidblocks-minio
      - solidblocks-rds-postgresql
      - solidblocks-rds-postgresql-test
      - solidblocks-debug-container
      - solidblocks-cloud-init
      - solidblocks-hetzner
      - solidblocks-hetzner-test
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: solidblocks-hetzner-nuke/do build
      - name: Test
        run: solidblocks-hetzner-nuke/do test

  solidblocks-terraform:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: solidblocks-terraform/do build
      - name: Test
        run: solidblocks-terraform/do test

  solidblocks-hetzner:
    runs-on: ubuntu-latest
    needs:
      - solidblocks-cloud-init
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Build
        run: solidblocks-hetzner/do build
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-hetzner
          path: |
            solidblocks-hetzner/build/snippets/*

  solidblocks-hetzner-test:
    runs-on: ubuntu-latest
    needs:
      - solidblocks-hetzner
      - solidblocks-rds-postgresql
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        #test_name: [test-restore-local, test-restore-s3, test-arm, test-ssl]
        test_name: [ test-migration, test-restore-local, test-restore-s3, test-private-network, test-arm, test-ssl ]
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      HETZNER_DNS_API_TOKEN: ${{ secrets.HETZNER_DNS_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install postgresql-client
        run: sudo apt-get install -y postgresql-client
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Build
        run: solidblocks-hetzner/do build
      - name: Test
        run: solidblocks-hetzner/do ${{ matrix.test_name }}

  solidblocks-minio:
    name: solidblocks-minio
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: solidblocks-minio/do build
      - name: Test
        run: solidblocks-minio/do test
      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-minio-test
          path: |
            solidblocks-minio/test/build/reports/tests

  solidblocks-debug-container:
    name: solidblocks-debug-container
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: solidblocks-debug-container/do build
      - name: Test
        run: solidblocks-debug-container/do test
      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-debug-container-test
          path: |
            solidblocks-debug-container/build/reports/tests

  solidblocks-rds-postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: solidblocks-rds-postgresql/do build

  solidblocks-rds-postgresql-test:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    needs:
      - solidblocks-minio
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: solidblocks-rds-postgresql/do test
      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: solidblocks-rds-postgresql-test
          path: |
            solidblocks-rds-postgresql/test/build/reports/tests

  clean-cloud-resources:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      HETZNER_DNS_API_TOKEN: ${{ secrets.HETZNER_DNS_API_TOKEN }}
    if: ${{ always() }}
    needs:
      - solidblocks-shell
      - solidblocks-cloud-init
      - solidblocks-minio
      - solidblocks-rds-postgresql
      - solidblocks-rds-postgresql-test
      - solidblocks-hetzner
      - solidblocks-hetzner-test
      - solidblocks-debug-container
      - solidblocks-hetzner-nuke
      - solidblocks-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clean Cloud Resources
        run: ./do clean-hetzner

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - solidblocks-shell
      - solidblocks-cloud-init
      - solidblocks-minio
      - solidblocks-rds-postgresql
      - solidblocks-rds-postgresql-test
      - solidblocks-hetzner
      - solidblocks-hetzner-test
      - solidblocks-debug-container
      - solidblocks-hetzner-nuke
      - solidblocks-terraform
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Release Docker
        run: ./do release-docker
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            solidblocks-shell/solidblocks-shell-*.zip
            solidblocks-shell/snippets/*
            solidblocks-cloud-init/solidblocks-cloud-init-*.zip
            solidblocks-cloud-init/snippets/*
            solidblocks-hetzner/*.zip

  documentation:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - release
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Bootstrap
        run: ./do bootstrap
      - name: Build Documentation
        run: ./do build-documentation
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/documentation/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

